# Complex Numbers

***

In [1]:
import numpy as np

In [2]:
1 + 3j

(1+3j)

In [3]:
complex(1, 3)

(1+3j)

In [4]:
a = 1 - 3j
a

(1-3j)

In [5]:
b = 2 + 4j
b

(2+4j)

In [6]:
a + b

(3+1j)

In [7]:
a * b

(14-2j)

## Matrix Representation

The complex numbers $\mathbb{C}$ can be represented as matrices over the real numbers $\mathbb{R}$.

$
a + bi \longleftrightarrow
\begin{bmatrix}
a & -b \\
b & a \\
\end{bmatrix}
$

##### Addition

$(a_0 + b_0 i) + (a_1 + b_1 i) = (a_0 + a_1) + (b_0 + b_1) i$

$\begin{bmatrix}
a_0 & -b_0 \\
b_0 &  a_0 \\
\end{bmatrix} + 
\begin{bmatrix}
a_1 & -b_1 \\
b_1 &  a_1 \\
\end{bmatrix} = 
\begin{bmatrix}
(a_0 + a_1) & -(b_0 + b_1) \\
(b_0 + b_1) &  (a_0 + a_1) \\
\end{bmatrix}
$

##### Multiplication

$(a_0 + b_0 i) \times (a_1 + b_1 i) = (a_0 a_1 - b_0 b_1) + (a_0 b_1 + b_0 a_1) i$

$\begin{bmatrix}
a_0 & -b_0 \\
b_0 &  a_0 \\
\end{bmatrix}
\begin{bmatrix}
a_1 & -b_1 \\
b_1 &  a_1 \\
\end{bmatrix} = 
\begin{bmatrix}
(a_0 a_1 - b_0 b_1) & -(a_0 b_1 + b_0 a_1) \\
(a_0 b_1 + b_0 a_1) & (a_0 a_1 - b_0 b_1) \\
\end{bmatrix}
$

In [8]:
A = np.array([[1, 3], [-3, 1]])
A

array([[ 1,  3],
       [-3,  1]])

In [9]:
B = np.array([[2, -4], [4, 2]])
B

array([[ 2, -4],
       [ 4,  2]])

In [10]:
A @ B

array([[14,  2],
       [-2, 14]])

## Other Operations

##### Conjugate as Transpose

$c = a + bi$

$\begin{bmatrix} a & -b \\ b & a \end{bmatrix}$

$\begin{bmatrix} a & -b \\ b & a \end{bmatrix}^T = \begin{bmatrix} a & b \\ -b & a \end{bmatrix}$

$c^* = a - bi$

$\begin{bmatrix} a & b \\ -b & a \end{bmatrix}$

##### Absolute Value

$c = a + bi$

$c^* = a - bi$

$cc^* = (a + bi) (a - bi) = a^2 + b^2$

$|cc^*| = \sqrt{a^2 + b^2}$

$\begin{bmatrix} a & -b \\ b & a \end{bmatrix}\begin{bmatrix} a & b \\ -b & a \end{bmatrix} = \begin{bmatrix} a^2 + b^2 & 0 \\ 0 & a^2 + b^2 \end{bmatrix} = a^2 + b^2 \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

$\left|\begin{bmatrix} a & -b \\ b & a \end{bmatrix}\right| = \sqrt{a^2 + b^2} \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

***

#### End