<a href="https://colab.research.google.com/github/ianmcloughlin/quantum-notebooks/blob/main/quantum_latin_squares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quantum Latin Squares

***

In [1]:
# Numerical arrays.
import numpy as np

In [2]:
# Print options.
np.set_printoptions(formatter={'complex_kind': '{:.2f}'.format, 'float': '{:.2f}'.format})

In [3]:
'{:.2f}'

'{:.2f}'

## Latin Squares
***

A latin square of order $n$ is an $n \times n$ array over a set $S$ of order $n$ such that each element of $S$ appears exactly once in each row and in each column.

In [4]:
# A 3x3 Latin square over {1,2,3}.
ls_a = np.array([
  [1,2,3],
  [2,3,1],
  [3,1,2],
], dtype=int)

# Show.
print(ls_a)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [5]:

# Another 3x3 Latin square over {1,2,3}.
ls_b = np.array([
  [1,3,2],
  [2,1,3],
  [3,2,1],
], dtype=int)

# Show.
print(ls_b)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


## Mutually Orthogonal Latin Squares

***

Suppose $LS_1$ is Latin square of order $n$ over a set $S$ with entry $s_{ij}$ in row $i$ and column $j$.

Suppose that $LS_2$ is also a Latin square of order $n$ over a set $T$ with entry $t_{ij}$ in row $i$ and column $j$.

We say $LS_1$ and $LS_2$ are *mutually orthogonal* when all pairs $(s_{ij}, t_{ij})$ are distinct.

It must be, then, that the set $(s_{ij}, t_{ij})$ is equal to $S \times T$.

In [34]:
ls_a, ls_b

(array([[1, 2, 3],
        [2, 3, 1],
        [3, 1, 2]]),
 array([[1, 3, 2],
        [2, 1, 3],
        [3, 2, 1]]))

In [37]:
# Not so easy to see.
np.stack([ls_a, ls_b], axis=2)

array([[[1, 1],
        [2, 3],
        [3, 2]],

       [[2, 2],
        [3, 1],
        [1, 3]],

       [[3, 3],
        [1, 2],
        [2, 1]]])

In [38]:
# Use a trick.
lso = (10 * ls_a) + ls_b

# Show.
print(lso)

[[11 23 32]
 [22 31 13]
 [33 12 21]]


In [7]:
# All elements {(1,1), (1, 2), ..., (3,3)}.
els = np.sort(lso.flatten())

# Show.
print(els)

[11 12 13 21 22 23 31 32 33]


In [8]:
# Unique.
np.unique(els, return_counts=True)

(array([11, 12, 13, 21, 22, 23, 31, 32, 33]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1]))

## Quantum States

***

https://learning.quantum.ibm.com/course/basics-of-quantum-information/quantum-circuits#inner-products-orthonormality-and-projections

$\mathbb{C} = {a + bi \mid a, b \in \mathbb{R}}$

$c^* = a - bi$ where $c = a + bi$

$\vert x \rangle = \begin{bmatrix} x_0 & x_1 & \ldots & x_{n-1} \end{bmatrix}$

$\vert y \rangle = \begin{bmatrix} y_0 & y_1 & \ldots & y_{n-1} \end{bmatrix}$

$\langle x \vert = \begin{bmatrix} x_0^* \\ x_1^* \\ \vdots \\ x_{n-1}^* \end{bmatrix}$

$\langle x \vert y \rangle = x_0^*y_0 + x_1^*y_1 + \ldots + x_{n-1}^*y_{n-1}$

## Quantum Latin Squares

***

https://www.cs.ox.ac.uk/qpl2015/preproceedings/55.pdf

A quantum Latin squre of order $n$ is an $n \times n$ array of elements of $\mathbb{C}^n$ such that for each row and each column, the elements form an orthonormal basis for $\mathbb{C}^n$.

In [9]:
# Normalized element of C^4.
# 1/sqrt(5)i |0> + 2/sqrt(5)|3>
# 1/sqrt(5)i |0> + 0.0 |1> + 0.0 |2> + 2/sqrt(5)|3>
x1 = np.array([
    complex(0.0             , 1.0/np.sqrt(5.0)),
    complex(0.0             , 0.0             ),
    complex(0.0             , 0.0             ),
    complex(2.0/np.sqrt(5.0), 0.0             ),
], dtype=complex)

In [10]:
# Show vector.
print(x1)

[0.00+0.45j 0.00+0.00j 0.00+0.00j 0.89+0.00j]


In [11]:
# Bra from ket.
bra_x1 = x1.conjugate().transpose()

# Show bra.
print(bra_x1)

[0.00-0.45j 0.00-0.00j 0.00-0.00j 0.89-0.00j]


In [12]:
# Show it's normalized.
norm_x1 = x1.conjugate().transpose() @ x1

# Show normalisation - single values aren't formatted by numpy.
print(f'{norm_x1:.2f}')

1.00+0.00j


In [13]:
# Another normalised element of C^4.
x2 = np.array([
    complex(2.0 / np.sqrt(5.0), 0.0               ),
    complex(0.0,                0.0               ),
    complex(0.0,                0.0               ),
    complex(0.0,                1.0 / np.sqrt(5.0)),
])

In [39]:
# Show vector.
print(x2)

[0.89+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.45j]


In [40]:
# Show it's normalized.
norm_x2 = x2.conjugate().transpose() @ x2

# Show normalisation.
print(f"{norm_x2:.2f}")

1.00+0.00j


In [41]:
# Show |x1> and |x2> again.
print(x1)
print(x2)

[0.00+0.45j 0.00+0.00j 0.00+0.00j 0.89+0.00j]
[0.89+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.45j]


In [45]:
# <x2| - note it's a 1D array so we can't transpose - it doesn't matter.
print(x2.conjugate())

[0.89-0.00j 0.00-0.00j 0.00-0.00j 0.00-0.45j]


In [47]:
# <x2|x1>
x2x1 = x2.conjugate().transpose() @ x1

# Show orthogonality.
print(f"{x2x1:.2f}")

0.00-0.00j


## All Orthonormality

***

In [49]:
# Create all zeros.
qls = np.zeros((4, 4, 4), dtype=complex)

# Show.
qls

array([[[0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j]],

       [[0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j]],

       [[0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j]],

       [[0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
        [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j]]])

In [50]:
# Convenience.
rsq2 = 1.0 / np.sqrt(2.0) # 1/√2
rsq5 = 1.0 / np.sqrt(5.0) # 1/√5


In [53]:
# Musto's example.
qls[0,0] = [1.0, 0.0, 0.0, 0.0] # |0>
qls[0,1] = [0.0, 1.0, 0.0, 0.0] # |1>
qls[0,2] = [0.0, 0.0, 1.0, 0.0] # |2>
qls[0,3] = [0.0, 0.0, 0.0, 1.0] # |3>

qls[1,0] = [0.0, rsq2, -rsq2, 0.0] # 1/√2|1> + (-1/√2)|2>
qls[1,1] = [complex(0.0, rsq5), 0.0, 0.0, 2.0 * rsq5] # (1/√5)i|0> + 2/√5|3>
qls[1,2] = [2.0 * rsq5, 0.0, 0.0, complex(0.0, rsq5)] # 2/√5|0> + (1/√5)i|3>
qls[1,3] = [0.0, rsq2, rsq2, 0.0] # 1/√2|1> + 1/√2|2>

qls[2,0] = [0.0, rsq2, rsq2, 0.0] # 1/√2|1> + 1/√2|2>
qls[2,1] = [2.0 * rsq5, 0.0, 0.0, complex(0.0, rsq5)] # 2/√5|0> + (1/√5)i|3>
qls[2,2] = [complex(0.0, rsq5), 0.0, 0.0, 2.0 * rsq5] # (1/√5)i|0> + 2/√5|3>
qls[2,3] = [0.0, rsq2, -rsq2, 0.0] # 1/√2|1> + (-1/√2)|2>

qls[3,0] = [0.0, 0.0, 0.0, 1.0] # |3>
qls[3,1] = [0.0, 0.0, 1.0, 0.0] # |2>
qls[3,2] = [0.0, 1.0, 0.0, 0.0] # |1>
qls[3,3] = [1.0, 0.0, 0.0, 0.0] # |0>

In [54]:
# Show.
print(qls)

[[[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
  [0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
  [0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
  [0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]]

 [[0.00+0.00j 0.71+0.00j -0.71+0.00j 0.00+0.00j]
  [0.00+0.45j 0.00+0.00j 0.00+0.00j 0.89+0.00j]
  [0.89+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.45j]
  [0.00+0.00j 0.71+0.00j 0.71+0.00j 0.00+0.00j]]

 [[0.00+0.00j 0.71+0.00j 0.71+0.00j 0.00+0.00j]
  [0.89+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.45j]
  [0.00+0.45j 0.00+0.00j 0.00+0.00j 0.89+0.00j]
  [0.00+0.00j 0.71+0.00j -0.71+0.00j 0.00+0.00j]]

 [[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]
  [0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
  [0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
  [1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]]]


In [25]:
# Norm.
np.apply_along_axis(lambda x: np.vdot(x, x), 2, qls)

array([[1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j]])

In [26]:
# Norm again.
np.sum(np.conjugate(qls) * qls, axis=2)

array([[1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j],
       [1.00+0.00j, 1.00+0.00j, 1.00+0.00j, 1.00+0.00j]])

In [27]:
# First row.
qls[0]

array([[1.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
       [0.00+0.00j, 1.00+0.00j, 0.00+0.00j, 0.00+0.00j],
       [0.00+0.00j, 0.00+0.00j, 1.00+0.00j, 0.00+0.00j],
       [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 1.00+0.00j]])

In [28]:
# Orthonorm columns.

# Loop through rows.
for i in range(qls.shape[0]):
  # Blank line to separate rows.
  print()
  # Loop through columns.
  for j in range(qls.shape[1]):
    # Entries in row i.
    ri = qls[i]
    # Entry in row i, column j, conjugate
    ricj = np.conjugate(qls[i, j])
    # Inner product of entry in row i, column j and each element of row i.
    print(np.sum(ricj * ri, axis=1))


[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]


In [29]:
# First column.
qls[:,0]

array([[1.00+0.00j, 0.00+0.00j, 0.00+0.00j, 0.00+0.00j],
       [0.00+0.00j, 0.71+0.00j, -0.71+0.00j, 0.00+0.00j],
       [0.00+0.00j, 0.71+0.00j, 0.71+0.00j, 0.00+0.00j],
       [0.00+0.00j, 0.00+0.00j, 0.00+0.00j, 1.00+0.00j]])

In [30]:
# Orthonorm rows.

# Loop through columns.
for j in range(qls.shape[1]):
  # Blank line to separate cols.
  print()
  # Loop through rows.
  for i in range(qls.shape[0]):
    # Entries in col j.
    cj = qls[:, j]
    # Entry in row i, column j, conjugate
    ricj = np.conjugate(qls[i, j])
    # Inner product of entry in row i, column j and each element of column i.
    print(np.sum(ricj * cj, axis=1))


[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]

[1.00+0.00j 0.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 1.00+0.00j 0.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 1.00+0.00j 0.00+0.00j]
[0.00+0.00j 0.00+0.00j 0.00+0.00j 1.00+0.00j]


## Discrete Fourier Transform

***

$x = \{x_n\} := (x_0, x_1, \ldots, x_{n-1})$

$\textbf{DFT}(x) = X = \{X_k\} := (X_0, X_1, \ldots, X_{n-1})$

$X_k = \sum_{n=0}^{N-1} x_n e^{-i2\pi\frac{k}{N}n}$

$r_k = (e^{-i2\pi\frac{k}{N}n} \textrm{ for } n \textrm{ in } [N] )$

$r_k = e^{\frac{2ik\pi}{N}}(e^n \textrm{ for } n \textrm{ in } [N] )$

$X_k = r_k \cdot x$

$ M = [\frac{kn}{N}]_{kn} $

In [31]:
N = 12
M = np.array([[((k * n) / N) % 1 for n in range(N)] for k in range(N)])
print(M)

[[0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 0.08 0.17 0.25 0.33 0.42 0.50 0.58 0.67 0.75 0.83 0.92]
 [0.00 0.17 0.33 0.50 0.67 0.83 0.00 0.17 0.33 0.50 0.67 0.83]
 [0.00 0.25 0.50 0.75 0.00 0.25 0.50 0.75 0.00 0.25 0.50 0.75]
 [0.00 0.33 0.67 0.00 0.33 0.67 0.00 0.33 0.67 0.00 0.33 0.67]
 [0.00 0.42 0.83 0.25 0.67 0.08 0.50 0.92 0.33 0.75 0.17 0.58]
 [0.00 0.50 0.00 0.50 0.00 0.50 0.00 0.50 0.00 0.50 0.00 0.50]
 [0.00 0.58 0.17 0.75 0.33 0.92 0.50 0.08 0.67 0.25 0.83 0.42]
 [0.00 0.67 0.33 0.00 0.67 0.33 0.00 0.67 0.33 0.00 0.67 0.33]
 [0.00 0.75 0.50 0.25 0.00 0.75 0.50 0.25 0.00 0.75 0.50 0.25]
 [0.00 0.83 0.67 0.50 0.33 0.17 0.00 0.83 0.67 0.50 0.33 0.17]
 [0.00 0.92 0.83 0.75 0.67 0.58 0.50 0.42 0.33 0.25 0.17 0.08]]


In [32]:
d = np.array([1,1,0,1,1,1,1,0,1,0,0,0], int)

In [33]:
d.shape

(12,)

***

### End