<a href="https://colab.research.google.com/github/ianmcloughlin/quantum-notebooks/blob/main/quantum_latin_squares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quantum Latin Squares

***

In [ ]:
# Numerical arrays.
import numpy as np

## Latin Squares
***

A latin square of order $n$ is an $n \times n$ array over a set $S$ of order $n$ such that each element of $S$ appears exactly once in each row and in each column.

In [ ]:
# A 3x3 Latin square over {1,2,3}.
ls_a = np.array([
  [1,2,3],
  [2,3,1],
  [3,1,2],
], dtype=int)

# Show.
print(ls_a)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [ ]:

# Another 3x3 Latin square over {1,2,3}.
ls_b = np.array([
  [1,3,2],
  [2,1,3],
  [3,2,1],
], dtype=int)

# Show.
print(ls_b)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


## Mutually Orthogonal Latin Squares

***

Suppose $LS_1$ is Latin square of order $n$ over a set $S$ with entry $s_{ij}$ in row $i$ and column $j$.

Suppose that $LS_2$ is also a Latin square of order $n$ over a set $T$ with entry $t_{ij}$ in row $i$ and column $j$.

We say $LS_1$ and $LS_2$ are *mutually orthogonal* when all pairs $(s_{ij}, t_{ij})$ are distinct.

It must be, then, that the set $(s_{ij}, t_{ij})$ is equal to $S \times T$.

In [ ]:
# ls_a and ls_b are orthogonal.
lso = (10 * ls_a) + ls_b

# Show.
print(lso)

[[11 23 32]
 [22 31 13]
 [33 12 21]]


In [ ]:
# All elements {(1,1), (1, 2), ..., (3,3)}.
els = np.sort(lso.flatten())

# Show.
print(els)

[11 12 13 21 22 23 31 32 33]


In [ ]:
# Unique.
np.unique(els, return_counts=True)

(array([11, 12, 13, 21, 22, 23, 31, 32, 33]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1]))

## Quantum States

***

https://learning.quantum.ibm.com/course/basics-of-quantum-information/quantum-circuits#inner-products-orthonormality-and-projections

$\mathbb{C}$

$\vert y \rangle = \begin{bmatrix} y_0 & y_1 & \ldots & y_n \end{bmatrix}$

$\langle x \vert = \begin{bmatrix} \bar{x_0} \\ \bar{x_1} \\ \vdots \\ \bar{x_n} \end{bmatrix}$

$\langle x \vert y \rangle = \bar{x_0}y_0 + \bar{x_1}y_1 + \ldots + \bar{x_n}y_n$

## Quantum Latin Squares

***

A quantum Latin squre of order $n$ is an $n \times n$ array of elements of $\mathbb{C}^n$ such that for each row and each column, the elements form an orthonormal basis for $\mathbb{C}^n$.

In [ ]:
# Normalized element of C^4.
x1 = np.array([
    complex(0.0, 1.0 / np.sqrt(5.0)),
    complex(0.0, 0.0),
    complex(0.0, 0.0),
    complex(2.0 / np.sqrt(5.0), 0.0),
])

In [ ]:
# Show vector.
print([f"{i:.2f}" for i in x1])

['0.00+0.45j', '0.00+0.00j', '0.00+0.00j', '0.89+0.00j']


In [ ]:
# Show it's normalized.
norm_x1 = x1.conjugate().transpose() @ x1

# Show normalisation.
print(f"{norm_x1:.2f}")

1.00+0.00j


In [ ]:
# Another normalised element of C^4.
x2 = np.array([
    complex(2.0 / np.sqrt(5.0), 0.0),
    complex(0.0, 0.0),
    complex(0.0, 0.0),
    complex(0.0, 1.0 / np.sqrt(5.0)),
])

In [ ]:
# Show vector.
print([f"{i:.2f}" for i in x2])

['0.89+0.00j', '0.00+0.00j', '0.00+0.00j', '0.00+0.45j']


In [ ]:
# Show it's normalized.
norm_x2 = x2.conjugate().transpose() @ x2

# Show normalisation.
print(f"{norm_x2:.2f}")

1.00+0.00j


In [ ]:
# Show |x1> and |x2> again.
print([f"{i:.2f}" for i in x1])
print([f"{i:.2f}" for i in x2])

['0.00+0.45j', '0.00+0.00j', '0.00+0.00j', '0.89+0.00j']
['0.89+0.00j', '0.00+0.00j', '0.00+0.00j', '0.00+0.45j']


In [ ]:
# <x2|
print([f"{i:.2f}" for i in x2.conjugate()])

['0.89-0.00j', '0.00-0.00j', '0.00-0.00j', '0.00-0.45j']


In [ ]:
# <x2|x1>
x2x1 = x2.conjugate().transpose() @ x1

In [ ]:
# Show orthogonality.
print(f"{x2x1:.2f}")

0.00+0.00j


***

### End